services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Downloads:/app/Downloads
    user: root  # Executa como root para garantir que tenha permissões